### PR TITLE
ETSWORK-9827 add LICENSE and servicenow webhook code

### PR DESCRIPTION
**Pull request by drekaygran**
Upload ServiceNow webhook code and add license file

### CODE REVIEW

**Comment by finbarc** [comment]
I had a quick check of the files and it looks similar to what we had in GitLab.
I can't find a way to import this into ServiceNow studio to verify it there until this is merged into head (please let me know if you found a way) as it can't find the checksum file in head on the initial import and there doesn't seem to be a way to import a branch.
If Team Up would like an overview of the ServiceNow webhook app I can do that if we want to set up a meeting or something.

**Review by coreyjv — DISMISSED** [review]
Thank you for adding the `LICENSE` file!

**Comment by drekaygran** [comment]
@finbarc I think it is possible to specify a branch on upload. I'll give this a try before merging.

**Comment by drekaygran** [comment]
Update: I am able to import this branch from GitHub into my ServiceNow developer instance. On creating a new request, cards are sent to the submitter and approver and can successfully be actioned on by the approver.

**Review by coreyjv — APPROVED** [review]

**Review by alexanderjdee — APPROVED** [review]

**Pull request merged**
